### ISSUE TITLE
Appomattox 0001: Incredibly small, cyclical flows for entire study period

### ISSUE THREAD

**Issue by hdaniel7** [HARPgroup/cbp6#137]
For the river segment [JA5_7480_0001](http://deq2.bse.vt.edu/d.dh/ows-watershed-dash-info/68373) [George F. Brasfield Dam], flows are identical between the base and climate change scenarios.  The maximum metrics peak at under 10cfs, while minimum metrics are all above 4cfs.  Flows all appear to be perfectly cyclical. The two segments upstream, [JA2_7570_7480](http://deq2.bse.vt.edu/d.dh/ows-watershed-dash-info/68323) [West Creek (Deep Creek, Appomattox)] and [JA4_7470_7480](http://deq2.bse.vt.edu/d.dh/ows-watershed-dash-info/67969) [Appomattox River] have both been run and appear to have reasonable flows over the study period.

One other thing to note: Although segment JA5_7480_0001 is a 0001 segment (used to denote an outlet segment), it does have a segment attached downstream -- segment [JA5_7520_0000](http://deq2.bse.vt.edu/d.dh/ows-watershed-dash-info/68372/) [Appomattox River below Brasfield Dam] -- perhaps the 0001 segment is only meant to model the impoundment and not accurately reflect Appomattox River flows?  Note that the downstream 0000 segment is a coastal segment, though.

Rob guesses that an alternative runoff set or some other set is hardwired into the JA5_7480_0001 segment -- something to dig into when he returns.

Dashboards comparing p6 base and climate change scenarios for each of these segments follow:

[Appomattox_0001_Vahydro_Vs_Vahydro_Dashboard_2019.pdf](https://github.com/HARPgroup/cbp6/files/3780061/Appomattox_0001_Vahydro_Vs_Vahydro_Dashboard_2019.pdf)

[JA2_7570_7480_WestCreek_Vahydro_Vs_Vahydro_Dashboard_2019.pdf](https://github.com/HARPgroup/cbp6/files/3780026/JA2_7570_7480_WestCreek_Vahydro_Vs_Vahydro_Dashboard_2019.pdf)

[JA4_7470_7480_Appomattox_Vahydro_Vs_Vahydro_Dashboard_2019.pdf](https://github.com/HARPgroup/cbp6/files/3780028/JA4_7470_7480_Appomattox_Vahydro_Vs_Vahydro_Dashboard_2019.pdf)

**Comment by rburghol** [comment]
Need to dive deeper into whats happening. Locate the land river segment objects and chart the unit are runoff values, and locate the "1. local runoff inflows" objects and see if they are passing the correct flows.

**Comment by hdaniel7** [comment]
The land river segment objects corresponding to river segment JA5_7480_0001 are:
- [N51007_JA5_7480_0001](http://deq2.bse.vt.edu/d.dh/ows-watershed-dash-info/450984)
- [N51053_JA5_7480_0001](http://deq2.bse.vt.edu/d.dh/ows-watershed-dash-info/450985)
- [N51135_JA5_7480_0001](http://deq2.bse.vt.edu/d.dh/ows-watershed-dash-info/450986)
- [N51041_JA5_7480_0001](http://deq2.bse.vt.edu/d.dh/ows-watershed-dash-info/450987)

The land use unit flow files are located at:
- /media/NAS/omdata/p6/out/land/CFBASE30Y20180615/eos/N51007_0111-0211-0411.csv
- /media/NAS/omdata/p6/out/land/CFBASE30Y20180615/eos/N51053_0111-0211-0411.csv
- /media/NAS/omdata/p6/out/land/CFBASE30Y20180615/eos/N51135_0111-0211-0411.csv
- /media/NAS/omdata/p6/out/land/CFBASE30Y20180615/eos/N51041_0111-0211-0411.csv
What type of charting should I do on these land use unit runoff values?  Are there a select few land uses I should plot (such as the highest 3 flows for each land river segment)?

[Here](http://deq2.bse.vt.edu/d.dh/om-model-info/4823312)'s a link to the "1. local runoff inflow" object for the George F. Brasfield Dam river segment -- I tried digging deeper into this object but was unable to find where it lists what flows are being passed.  I figured they would be linked with the "CBP6 Runoff" feature through the "om element connection" -- this "om element connection" has a value of 343802 -- I searched for the feature with a hydroID of 343802 and found [this](http://deq2.bse.vt.edu/d.dh/admin/content/dh_features/manage/343802) property with a name of "null" with a drainage area property of 0.073 sq. mi. and mean flow properties ranging from a min of 0.01cfs in Nov. to a max of 0.157cfs in Mar. 

For comparison, I looked into the Appomattox River river segment one above this segment -- This river segment's "om element connection" within the "CBP6 Runoff" feature pointed to hydroID 342916 corresponding to "Flatrock Creek" with a drainage area of 3.062 sq. mi and mean flow properties ranging from a min of 0.746 cfs in Sep. to a max of 7.775 cfs in Nov.

One thing I noticed while digging through the downstream Craig Creek segment is that within the ["CB6 Runoff" feature](http://deq2.bse.vt.edu/d.dh/om-model-info/4729946), there is a property called "N51045_JU1_7690_7490" -- there are no such land-river segment properties attached to the "CBP6 Runoff" features of the Appomattox segments.  What is the significance of these land-river segment properties?

**Comment by hdaniel7** [comment]
@rburghol or by "chart the unit area runoff values" are you suggesting that I multiply the land use unit flows by the land use areas for each of these corresponding land-river segments, sum these flows across all of the land uses and land segments, aggregate these flows by their monthly mean, and check to ensure that they are the same as those that appear within [this](http://deq2.bse.vt.edu/d.dh/admin/content/dh_features/manage/343802) property associated with the CBP6 Runoff feature?

**Comment by rburghol** [comment]
No, no, nothing so hard :). Just learn to obtain the model output file for the landriver segment model element (very similar to river segment run file), and examine the Runit (or Qunit?) column, or get the "1. Local Runoff Inflows" element run file and look at the unit area outflow (Runit), and see if they're zero.

**Comment by hdaniel7** [comment]
You're right -- obtaining model output files for land-river segment model elements is very similar to getting them for the river segments -- [here](https://github.com/HARPgroup/cbp6/blob/master/R/vahydro_import_lrseg_data_cfs.R) is a new function to pull the land-river segment data for a VA Hydro model run (also thrown into the cbp6_functions.R file, so it'll be loaded when that file is sourced).

[Here](https://github.com/HARPgroup/cbp6/blob/master/analysis/Appomattox_0001_troubleshooting.R)'s a quick R script I've been using to troubleshoot this issue -- even without hydrographs, it is obvious that something is going majorly wrong.  The mean flow for the river segment is 7.08 cfs for this model run -- the sum of the mean flows for the four land-river segments comprising this river segment is 159.53 cfs.  This does not even include flows being passed from upstream river segments.

I also got the runfile for the "1. Local Runoff Inflows" element -- the only way I could figure to do this was by selecting the appropriate model scenario run (120) and clicking "Load Table Info".  For future reference, I then had to click "Download Complete Model Scenario Run File" which opened the log file in a new Chrome tab, copy and paste all of the data into a Notepad document to be saved as a .txt file, and then import the .txt file into Excel and save that as a .csv file -- this certainly isn't the most efficient way to get the data, but it's the first think that I came across that worked.  After loading this "1. Local Runoff Inflows" runfile into R, I took a quick look at the Runit column and noticed that the first few lines appeared to be equal to "Qmdc_unit" -- I then ran the R line "which(local.runoff.inflows$Runit != 'Qmdc_unit')" to confirm that every single Runit value in this runfile is equal to "Qmdc_unit" -- at the moment, I'm not entirely sure what this implies or is referencing in the model.

**Comment by rburghol** [comment]
Great find!  The Qmdc_unit is probably the issue, or perhaps more specifically, that entire Runit lookup table doesn't contain entries for the CBP6 flow scenarios.  Now, *why* it doesn't have those is complicated.  We had that "Qmdc" in there for use in a special analysis we did a while back, and it IS important to preserve that, but I expected that it would have been overwritten by my batch save to all Runit components.  So... this means we should be vigilant about 0 runoff results -- well, obviously we should be alert to zero flows... that is a vote for Dr. Scotts QA idea of showing flows as one moves downstream in a river network.

So, I corrected the Runit and reran the 120 scenario.  Results should be ready by todays meeting.  Thanks for sorting this out!  We can also review how to obtain the run file for the "1. Local..." elements without having to navigate through the UI.

**Comment by hdaniel7** [comment]
CC Run 121 has been completed -- here's the base vs CC dashboard.  Flows are consistently higher in the CC run, usually about 1-10%. Nothing is standing out to me as incorrect, so I'm closing this issue. Let me know if you see anything wonky about this segment in the future!
[Appomattox_120_vs_121.pdf](https://github.com/HARPgroup/cbp6/files/3790935/Appomattox_120_vs_121.pdf)
