### ISSUE TITLE
Jennings Randolph: Flows appear overly riverine and relatively unaffected by impoundment

### ISSUE THREAD

**Issue by hdaniel7** [HARPgroup/cbp6#139]
The following dashboards were generated using phase 6 base vs. climate change data and phase 6 base vs. gage flow data for segment [PU3_4450_4440](http://deq2.bse.vt.edu/d.dh/ows-watershed-dash-info/67816) [North Branch Potomac below Bloomington/Jennings Randolph] -- Rob noted that the flows appeared more riverine and less affected by the impoundment than would be expected -- it was noted that perhaps the local drainage area of the segment was incorrect.

[JenningsRandolph_base_vs_cc.pdf](https://github.com/HARPgroup/cbp6/files/3780134/JenningsRandolph_base_vs_cc.pdf)
[JenningsRandolph_gage_vs_base.pdf](https://github.com/HARPgroup/cbp6/files/3780154/JenningsRandolph_gage_vs_base.pdf)

I checked into it and realized that the total drainage area of the segment immediately upstream ([PU3_4451_4450](http://deq2.bse.vt.edu/d.dh/ows-watershed-dash-info/454132) [Bloomington/Jennings Randolph]) was incorrect -- I fixed this and began re-running the model.  I'll post the updated results here when the run is completed, but I'm not sure how much of a difference in the flow magnitudes this will make.

**Comment by rburghol** [comment]
I would also look at the downstream of Jennings segment. That one, in my quick look, appeared to have a too large local drainage. Also need to get with Joey and start looking at whether the impoundment actions are correctly simulated. First thing will be plotting Jennings versus below Jennings.

**Comment by hdaniel7** [comment]
After re-running the p6 base and climate change scenarios for segment PU3_4450_4440, I re-generated the dashboards -- they remain identical to the segments generated prior to the correction of PU3_4451_4450's cumulative drainage area (which makes sense, as the land use unit flow * land use area calculations are done using the local drainage area).  The segment directly below PU3_4450_4440, ([PU4_4440_3970](http://deq2.bse.vt.edu/d.dh/ows-watershed-dash-info/68220/) [Potomac River North Branch]) has a far smaller local drainage area of 3.28 sq. mi., if that is the segment that you're thinking of -- otherwise I'll work with Kevin to check the drainage areas of the segments in this drainage network in GIS on Wednesday

**Comment by hdaniel7** [comment]
Here's a dashboard showing Jennings vs. below Jennings for the phase 6 base scenario:
[Jennings_Randolph_Upstream_vs_Downstream.pdf](https://github.com/HARPgroup/cbp6/files/3781319/Jennings_Randolph_Upstream_vs_Downstream.pdf)

Here are a few quick hydrographs of Jennings vs below Jennings that I generated before just deciding to generate the whole dashboard for additional information -- I don't think they're very helpful but decided to throw them up here anyways:
![jennrand_log](https://user-images.githubusercontent.com/36606075/67729809-ed359d00-f9c8-11e9-9f12-c51ce822b0aa.png)
![jennrand_all](https://user-images.githubusercontent.com/36606075/67729804-e6a72580-f9c8-11e9-8efc-b800ed48deb4.png)
![jennrand_zoom](https://user-images.githubusercontent.com/36606075/67729781-d2632880-f9c8-11e9-98b8-d4ee88ecc347.png)

**Comment by rburghol** [comment]
4450_4440 is "North Branch Potomac **below** Bloomington/Jennings Randolph", not Jennings Randolph dam -- at least in vahydro -- if that is correct, I think it's local drainage area needs review, as well as the segment upstream of it, "Bloomington / Jennings Randolph" (4451_4450).

**Comment by hdaniel7** [comment]
Alright -- I'll work with @kevindandrea tomorrow morning to check over the local drainage areas in GIS for the segments in this drainage network.

**Comment by rburghol** [comment]
Not gis, in vahydro modeling dashboard.

**Comment by hdaniel7** [comment]
When you say "vahydro modeling dashboard", for the North Branch Potomac below Bloomington / Jennings Randolph, [this](http://deq2.bse.vt.edu/d.dh/?q=ows-watershed-dash-modeling/67816) is what I'm thinking of -- there is a "Watershed Local Drainage Area" property at the bottom of the dashboard, but I'm not sure what we should be checking this drainage area property against, if not the values from the GIS layer

**Comment by rburghol** [comment]
Go to the vahydro-1.0 model linked from that page, and then edit the "0. River Channel" element. You may verify later with gis, but am pretty sure you will see what needs to be sorted if you compare the Jennings and "Below Jennings" river channel settings.

**Comment by hdaniel7** [comment]
[Here](https://docs.google.com/spreadsheets/d/18SYTinpemdzCnI5DDufHuuZZ-OivJhKgMnHtKya-hMY/edit#gid=0)'s a quick analysis comparing the area properties against the areas listed within the "0. River Channel" element that I threw together -- and you're correct, the local drainage area for the Bloomington/Jennings Randolph and North Branch Potomac below Bloomington/Jennings Randolph segments as well as the cumulative drainage area for the Bloomington/Jennings Randolph are all too large within the "0. River Channel" elements.  Prior to today, I was unaware that the "0. River Channel" element stored the local and cumulative drainage areas used for running the VA Hydro model -- therefore we should check the areas stored within the "0. River Channel" elements for the other updated segments listed in [this issue](https://github.com/HARPgroup/cbp6/issues/100) (as well as probably the segment immediately upstream and downstream) to check if there are errors in those values as well.

I assume the solution to this issue is to update the areas in the "0. River Channel" element for these segments to the areas enumerated in the area properties, and then to re-run the model for these segments?

**Comment by rburghol** [comment]
Yeah, that's the ticket! If you change it in that interface that is all you need, then rerun and you're in business. Now, our choice of cache date is important. No need to re-run runoff, or any segments upstream of Jennings, so choose wisely :).

**Comment by hdaniel7** [comment]
I've got class for a few hours so I just forced a re-run since I won't be able to look at results for a few hours anyways :) I'll set a cache date of today when re-running the climate change and will have some comparisons between old and new results up later tonight!

**Comment by rburghol** [comment]
I would use the previous cache date, otherwise all the runoff will re run and there is no need for that. Or at least the cache date = date of the last Jennings segment run completion.
