### ISSUE TITLE
Phase 6 lrsegs

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/cbp6#86]
Joey mentioned that there were concerns about missing LRsegs in phase 6 dataset.  I wanted to give a quick check in on that, let you all know what I know, and if this proves lacking or unhelpful, ask that you all chime in on this github issue and we can all dig a little deeper.
What I know:
- I imported the lrsegs into vahydro -- stats:
  - The original dataset has 2,058 features, 
  - The dh_feature table also has 2,058 features 
- LRsegs for phase 6 in vahydro have:
  - bundle = 'landunit'
  - ftype = 'cbp6_lrsegs'
- The Phase 6 lrseg units *may not* be the same as the Phase 5, since the meteorological dataset has changed.
- The Phase 6 naming convention differs from that for Phase 5.3:
  - Phase 5.3 lrsegs had prefixes A, B & C
  - Phase 6 lrsegs has prefixes N, H and L
  - Ex. Craig Creek, segment JU3_7400_7510 (downstream a couple segs from our example):
      - Phase 5 & Phase 6 both have Riverseg: JU3_7400_7510
      - P5 has lrsegs: A51023 & A51005
      - P6 has lrsegs: N51005, N51023 and L51023

In some cases, the Phase 6 LRseg datasets are of a far higher resolution than the Phase 5.3.2 set.  Example below for Craig Creek segment 

Image 1: Phase 5.3.2 Land-River Segments:
![image](https://user-images.githubusercontent.com/4571170/61887666-0f061c00-aed0-11e9-99dd-30e9a56447c1.png)

Image 2: Phase 6 Land-River Segments
![image](https://user-images.githubusercontent.com/4571170/61887751-365ce900-aed0-11e9-91e2-50c6cbb754ae.png)

**Comment by hdaniel7** [comment]
I was unaware that the lrseg definition had changed so drastically between p5 and p6 -- initially I used the model command "cat /opt/model/p53/p532c-sova/config/seglists/JU3_7490_7400.land" to determine the p5 land segments which would be used by the model (A51045, A51071, F51045, F51071, A51121, A51161, F51121, F51161, A51023, and F51023) and used the updated naming convention to assume the p6 land segments would be N51045, N51071, H51045, H51071, N51121, N51161, H51121, H51161, N51023, and H51023 -- or the same numbers with the As switched to Ns and the Fs switched to Hs.

When linking them using VAHydro I realize that that sort of direct renaming of p5 to p6 segments does not work -- according to VA Hydro, JU3_7490_7400 has linked p532 land segments of A51023 and A51045 but has linked p6 land segments of L51023, N51045, N51005, N51023, and H51045 -- so I do not believe there really is an issue of missing land segments, the segments are just defined a bit differently in p6.

That said -- I'll generate the merged land use unit flow files for these Craig Creek land segments for your analysis.

**Comment by rburghol** [comment]
Thanks!  I will close this unless we see ample reason to re-open.
